DROP TABLE IF EXISTS `banner_item`;
CREATE TABLE `rest_banner_item`(
	`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`img_id` int(11) UNSIGNED NOT NULL COMMENT '外键，关联image表',
	`key_word` VARCHAR(100) NOT NULL COMMENT '执行关键字，根据不同的type含义不同',
	`type` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '跳转类型，可能导向商品，可能导向',
	`delete_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`banner_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '外键管理banner表',
	`update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)	
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT  CHARSET=utf8 COMMENT='banner的子项表';

DROP TABLE IF EXISTS `banner`;
CREATE TABLE `rest_banner`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'banner 名称，通常作为标识',
	`description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'banner 描述',
	`delete_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='banner 管理表';

CREATE TABLE `rest_img`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`url` VARCHAR(200)  NOT NULL DEFAULT '',
	`from` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
	`delete_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0'
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='crest_banner_item 图片表';

CREATE TABLE `rest_theme`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(100) NOT NULL DEFAULT '',
	`topic_img_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`delete_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`head_img_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ;

CREATE TABLE `rest_theme_product`(
	`theme_id` INT(11) UNSIGNED NOT NULL,
	`product_id` INT(11) UNSIGNED NOT NULL
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_product`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL DEFAULT '',
	`price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	`stock` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`category_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`main_img_url` VARCHAR(200) NOT NULL DEFAULT '',
	`from` TINYINT(1) NOT NULL DEFAULT '1',
	`create_time` INT(11) NOT NULL DEFAULT '0',
	`update_time` INT(11) NOT NULL DEFAULT '0',
	`summary` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	`img_id` INT NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `category_id`(`category_id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_category`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
	`top_img_id` INT(11) NOT NULL DEFAULT '0',
	`description` VARCHAR(255) NOT NULL DEFAULT '',
	`delete_time` INT NOT NULL DEFAULT '0',
	`update_time` INT NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `category_name`(`name`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_user`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`openid` INT UNSIGNED NOT NULL DEFAULT '0',
	`nickname` VARCHAR(50) NOT NULL DEFAULT '',
	`extend` VARCHAR(50) NOT NULL DEFAULT '',
	`delete_time` INT NOT NULL DEFAULT '0',
	`update_time` INT NOT NULL DEFAULT '0',
	`create_time` INT NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `user_openid` (`openid`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_product_img`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`img_id` INT UNSIGNED NOT NULL DEFAULT '0',
	`product_id` INT UNSIGNED NOT NULL DEFAULT '0',
	`order` INT UNSIGNED NOT NULL DEFAULT '0',
	`delete_time` INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `product_id`(`product_id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_product_property`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
	`detail` VARCHAR(200) NOT NULL DEFAULT '',
	`product_id` INT NOT NULL DEFAULT '0',
	`delete_time` INT NOT NULL DEFAULT '0',
	`update_time` INT NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `product_id` (`product_id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `rest_user_address`(
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
	`mobile` VARCHAR(15) NOT NULL DEFAULT '',
	`province` VARCHAR(30) NOT NULL DEFAULT '',
	`city` VARCHAR(30) NOT NULL DEFAULT '',
	`county` VARCHAR(30) NOT NULL DEFAULT '',
	`detail` VARCHAR(100) NOT NULL DEFAULT '',
	`userid` INT UNSIGNED NOT NULL DEFAULT '0',
	`create_time` INT UNSIGNED NOT NULL DEFAULT '0',
	`delete_time` INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY(`id`),
	KEY `userid`(`userid`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;